"""Added daily usage table

Revision ID: 7051ddadde0a
Revises: d6579e75e5a2
Create Date: 2026-01-16 17:47:50.048542

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7051ddadde0a"
down_revision: Union[str, Sequence[str], None] = "d6579e75e5a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_platform_usage",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("platform", sa.String(length=255), nullable=True),
        sa.Column("total_post_generated", sa.Integer(), nullable=True),
        sa.Column("total_token_used", sa.Integer(), nullable=True),
        sa.Column("total_latency_ms", sa.Integer(), nullable=True),
        sa.Column("average_latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "date", sa.Date(), server_default=sa.text("(CURRENT_DATE)"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("daily_platform_usage")
    # ### end Alembic commands ###
