"""added string with value like 255

Revision ID: df9f052c9cfd
Revises: 32e12d463b13
Create Date: 2026-01-16 10:16:49.227832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9f052c9cfd'
down_revision: Union[str, Sequence[str], None] = '32e12d463b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_generation_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('content_post_id', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=255), nullable=False),
    sa.Column('token_used', sa.Integer(), nullable=True),
    sa.Column('ai_provider', sa.String(length=255), nullable=True),
    sa.Column('model_version', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'STARTED', 'RETRY', 'FAILURE', 'SUCCESS', name='content_generation_status', native_enum=False), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_generation_events')
    # ### end Alembic commands ###
