from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional
from uuid import UUID


class UsageMetadataSchema(BaseModel):
    prompt_tokens: int = Field(..., description="Tokens from the initial prompt")
    candidates_tokens: int = Field(..., description="Tokens generated by the AI")
    total_tokens: int = Field(..., description="Sum of prompt and candidate tokens")


class JobResponseSchema(BaseModel):
    id: UUID
    job_type: str
    progress: int
    status: str
    retries: int
    error: Optional[str]
    created_at: datetime
    updated_at: datetime
    ai_provider: Optional[str]
    usage_metadata: Optional[UsageMetadataSchema] = None

    class Config:
        from_attributes = True


class ContentJobCreateSchema(BaseModel):
    job_type: str


class JobStatusResponse(BaseModel):
    status: str
    progress: int


class JobRetryResponse(BaseModel):
    message: str
