"""added new content models

Revision ID: 2cfe62eb5ec9
Revises: 
Create Date: 2025-12-28 12:18:07.890139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2cfe62eb5ec9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_posts', 'ai_key_points')
    op.drop_column('content_posts', 'ai_summary')
    op.add_column('generated_assets', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('generated_assets', sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='asset_status'), nullable=False))
    op.add_column('generated_assets', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.add_column('generated_assets', sa.Column('latency_ms', sa.Integer(), nullable=True))
    op.add_column('generated_assets', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('generated_assets', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('generated_assets', 'job_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('generated_assets', 'variant_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('generated_assets', 'ai_provider',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('generated_assets', 'model_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('generated_assets', 'prompt_version',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_index(op.f('ix_generated_assets_content_post_id'), 'generated_assets', ['content_post_id'], unique=False)
    op.create_index(op.f('ix_generated_assets_job_id'), 'generated_assets', ['job_id'], unique=False)
    op.create_index(op.f('ix_generated_assets_platform'), 'generated_assets', ['platform'], unique=False)
    op.drop_constraint(op.f('generated_assets_job_id_fkey'), 'generated_assets', type_='foreignkey')
    op.create_foreign_key(None, 'generated_assets', 'content_jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_column('generated_assets', 'metaData')
    op.add_column('visual_assets', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('visual_assets', 'metaData')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visual_assets', sa.Column('metaData', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('visual_assets', 'meta_data')
    op.add_column('generated_assets', sa.Column('metaData', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'generated_assets', type_='foreignkey')
    op.create_foreign_key(op.f('generated_assets_job_id_fkey'), 'generated_assets', 'content_jobs', ['job_id'], ['id'])
    op.drop_index(op.f('ix_generated_assets_platform'), table_name='generated_assets')
    op.drop_index(op.f('ix_generated_assets_job_id'), table_name='generated_assets')
    op.drop_index(op.f('ix_generated_assets_content_post_id'), table_name='generated_assets')
    op.alter_column('generated_assets', 'prompt_version',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('generated_assets', 'model_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('generated_assets', 'ai_provider',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('generated_assets', 'variant_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('generated_assets', 'job_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('generated_assets', 'updated_at')
    op.drop_column('generated_assets', 'is_active')
    op.drop_column('generated_assets', 'latency_ms')
    op.drop_column('generated_assets', 'tokens_used')
    op.drop_column('generated_assets', 'status')
    op.drop_column('generated_assets', 'meta_data')
    op.add_column('content_posts', sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('content_posts', sa.Column('ai_key_points', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
