"""adde progress in job

Revision ID: 33eb4c62c663
Revises: 2f271a9859ad
Create Date: 2026-01-05 17:51:33.687232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33eb4c62c663'
down_revision: Union[str, Sequence[str], None] = '2f271a9859ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_jobs', sa.Column('progress', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_jobs', 'progress')
    # ### end Alembic commands ###
