"""initial_schema

Revision ID: 527ae39e3a69
Revises: 
Create Date: 2026-01-10 12:02:03.265176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '527ae39e3a69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ctaLink', sa.String(), nullable=False),
    sa.Column('ctaType', sa.Enum('READ_BLOG', 'VISITWEBSITE', 'SIGN_UP', 'LEARN_MORE', 'WATCH_VIDEO', 'DOWNLOAD', 'NONE', name='cta_type'), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('outline', sa.String(), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('audience', sa.String(length=100), nullable=True),
    sa.Column('content_goal', sa.String(length=50), nullable=True),
    sa.Column('platforms', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'GENERATED', 'FAILED', name='content_status'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_post_id', sa.UUID(), nullable=False),
    sa.Column('raw_ai_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('ai_provider', sa.String(length=30), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('usage_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'STARTED', 'RETRY', 'FAILURE', 'SUCCESS', name='job_status'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['content_post_id'], ['content_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_jobs_content_post_id'), 'content_jobs', ['content_post_id'], unique=False)
    op.create_table('generated_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_post_id', sa.UUID(), nullable=False),
    sa.Column('previous_version_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['content_post_id'], ['content_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['content_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_version_id'], ['generated_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_assets_content_post_id'), 'generated_assets', ['content_post_id'], unique=False)
    op.create_index(op.f('ix_generated_assets_job_id'), 'generated_assets', ['job_id'], unique=False)
    op.create_index(op.f('ix_generated_assets_platform'), 'generated_assets', ['platform'], unique=False)
    op.create_table('visual_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_post_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('slide_index', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('subtext', sa.String(length=500), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['content_post_id'], ['content_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['content_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visual_assets')
    op.drop_index(op.f('ix_generated_assets_platform'), table_name='generated_assets')
    op.drop_index(op.f('ix_generated_assets_job_id'), table_name='generated_assets')
    op.drop_index(op.f('ix_generated_assets_content_post_id'), table_name='generated_assets')
    op.drop_table('generated_assets')
    op.drop_index(op.f('ix_content_jobs_content_post_id'), table_name='content_jobs')
    op.drop_table('content_jobs')
    op.drop_table('content_posts')
    # ### end Alembic commands ###
