"""created contentpost, contentjob, asset, visuals

Revision ID: 9de3a5a2101c
Revises: 
Create Date: 2026-01-02 11:29:34.407040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9de3a5a2101c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_jobs', sa.Column('ai_provider', sa.String(length=30), nullable=True))
    op.add_column('content_jobs', sa.Column('model_version', sa.String(length=50), nullable=True))
    op.add_column('content_jobs', sa.Column('prompt_version', sa.String(length=20), nullable=True))
    op.add_column('content_jobs', sa.Column('usage_metadata', sa.JSON(), nullable=True))
    op.add_column('generated_assets', sa.Column('previous_version_id', sa.UUID(), nullable=True))
    op.add_column('generated_assets', sa.Column('version', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'generated_assets', 'generated_assets', ['previous_version_id'], ['id'], ondelete='CASCADE')
    op.drop_column('generated_assets', 'prompt_version')
    op.drop_column('generated_assets', 'status')
    op.drop_column('generated_assets', 'error')
    op.drop_column('generated_assets', 'tokens_used')
    op.drop_column('generated_assets', 'variant_index')
    op.drop_column('generated_assets', 'latency_ms')
    op.drop_column('generated_assets', 'asset_type')
    op.drop_column('generated_assets', 'ai_provider')
    op.drop_column('generated_assets', 'model_name')
    op.add_column('visual_assets', sa.Column('job_id', sa.UUID(), nullable=False))
    op.add_column('visual_assets', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('visual_assets', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('visual_assets', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('visual_assets_generated_asset_id_fkey'), 'visual_assets', type_='foreignkey')
    op.create_foreign_key(None, 'visual_assets', 'content_jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_column('visual_assets', 'generated_asset_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visual_assets', sa.Column('generated_asset_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'visual_assets', type_='foreignkey')
    op.create_foreign_key(op.f('visual_assets_generated_asset_id_fkey'), 'visual_assets', 'generated_assets', ['generated_asset_id'], ['id'], ondelete='CASCADE')
    op.drop_column('visual_assets', 'updated_at')
    op.drop_column('visual_assets', 'is_active')
    op.drop_column('visual_assets', 'version')
    op.drop_column('visual_assets', 'job_id')
    op.add_column('generated_assets', sa.Column('model_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('generated_assets', sa.Column('ai_provider', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('generated_assets', sa.Column('asset_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('generated_assets', sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('generated_assets', sa.Column('variant_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('generated_assets', sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('generated_assets', sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('generated_assets', sa.Column('status', postgresql.ENUM('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='asset_status'), autoincrement=False, nullable=False))
    op.add_column('generated_assets', sa.Column('prompt_version', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'generated_assets', type_='foreignkey')
    op.drop_column('generated_assets', 'version')
    op.drop_column('generated_assets', 'previous_version_id')
    op.drop_column('content_jobs', 'usage_metadata')
    op.drop_column('content_jobs', 'prompt_version')
    op.drop_column('content_jobs', 'model_version')
    op.drop_column('content_jobs', 'ai_provider')
    # ### end Alembic commands ###
