"""add cta fields to content_posts

Revision ID: dd6993565f78
Revises: 
Create Date: 2025-12-28 19:36:14.072575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd6993565f78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_posts', sa.Column('ctaType', sa.Enum('READ_BLOG', 'VISITWEBSITE', 'SIGN_UP', 'LEARN_MORE', 'WATCH_VIDEO', 'DOWNLOAD', 'NONE', name='cta_type'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_posts', 'ctaType')
    # ### end Alembic commands ###
