"""added new column latency ms

Revision ID: de047bdb8399
Revises: 527ae39e3a69
Create Date: 2026-01-16 07:52:31.505523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de047bdb8399'
down_revision: Union[str, Sequence[str], None] = '527ae39e3a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_jobs', sa.Column('latency_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_jobs', 'latency_ms')
    # ### end Alembic commands ###
