"""Description of changes

Revision ID: e3cffc8b8b32
Revises: 
Create Date: 2025-12-24 22:10:11.005657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3cffc8b8b32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_jobs_content_post_id'), table_name='content_jobs')
    op.drop_table('content_jobs')
    op.drop_table('content_posts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_posts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ctaLink', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('outline', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('audience', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('content_goal', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PROCESSING', 'GENERATED', 'FAILED', name='content_status'), autoincrement=False, nullable=False),
    sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_key_points', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='content_posts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('content_jobs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content_post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='job_status'), autoincrement=False, nullable=False),
    sa.Column('retries', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['content_post_id'], ['content_posts.id'], name=op.f('content_jobs_content_post_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('content_jobs_pkey'))
    )
    op.create_index(op.f('ix_content_jobs_content_post_id'), 'content_jobs', ['content_post_id'], unique=False)
    # ### end Alembic commands ###
