"""updated enum

Revision ID: e6d08f6ed108
Revises: 12d0d9e9d3ab
Create Date: 2026-01-05 19:40:46.568593

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e6d08f6ed108"
down_revision: Union[str, Sequence[str], None] = "12d0d9e9d3ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """CREATE TYPE JobStatus AS ENUM("PENDING","STARTED","RETRY","FAILURE","SUCCESS")"""
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
